import './globals.css';
import type { Metadata } from 'next';
import { Inter, Manrope } from 'next/font/google';
import Link from 'next/link';

export const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });
export const manrope = Manrope({ subsets: ['latin'], variable: '--font-manrope' });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang='en' className={`${inter.variable} ${manrope.variable}`}>
         <body className='app'>
            <nav>
               <ul>
                  <li>
                     <Link href='/'>Home</Link>
                  </li>
                  <li>
                     <Link href='/cookie'>Cookie</Link>
                  </li>
                  <li>
                     <Link href='/mui'>Mui</Link>
                  </li>
               </ul>
            </nav>
            {children}
         </body>
      </html>
   );
}
